# Generated by Django 5.1 on 2024-08-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
