# Generated by Django 5.1 on 2024-08-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0003_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='passwodrd',
        ),
    ]
