# Generated by Django 5.1 on 2024-08-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0005_rename_passwodrd_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.TextField(default='paciente'),
        ),
    ]
