# Generated by Django 5.1 on 2024-08-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0009_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='status',
            field=models.CharField(choices=[('pagar', 'Pagar')], default='pending', max_length=20),
        ),
    ]
