# Generated by Django 5.1 on 2024-08-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0010_scheduler_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('session_date', models.DateField()),
                ('session_time', models.TimeField()),
                ('physiotherapist', models.CharField(max_length=100)),
                ('session_notes', models.TextField()),
                ('session_type', models.CharField(max_length=50)),
            ],
        ),
    ]
