# Generated by Django 5.1 on 2024-09-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0011_sessionrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionRecord',
        ),
        migrations.RenameField(
            model_name='scheduler',
            old_name='extra',
            new_name='age',
        ),
    ]
