# Generated by Django 5.1 on 2024-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0012_delete_sessionrecord_rename_extra_scheduler_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='progress',
            field=models.TextField(default='Consulta'),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='value',
            field=models.TextField(default=100),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='status',
            field=models.CharField(choices=[('pagar', 'Pagar'), ('pago', 'Pago')], default='pending', max_length=20),
        ),
    ]
