# Generated by Django 4.2.11 on 2024-09-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_physiotherapy', '0014_alter_scheduler_status_alter_scheduler_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(max_length=50),
        ),
    ]
